#!/usr/bin/env python3
"""Replace PSE-time-log.csv rows from Jan-24 onward with full-fidelity harvest data."""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "PSE-time-log.csv"

# (Date, Description, Impact, Criteria, Source, Notes)
ROWS_2024_PLUS = [
    ("Jan-24", "Isovalent acquisition", "", "", "", "check w/Amy Gerrie on my impact"),
    ("Jan-24", "SRv6 for DC at Voltage Park", "medium", "biz", "", "presentation at EBC. Lead architect Drew Pletcher was interested for DC frontend, but did not follow through"),
    ("Jan-24", "SRv6 for SASE, SRv6 & ISE - really started to pursue SRv6 as a end-to-end solution with Josh Merrill", "high", "innov, span", "", "pulled in Darrin Miller (ISE DE) to include identity services in the architecture"),
    ("Jan-24", "MSFT 1.6T WAN/protocol design, SRv6, multi-plane ISIS, etc.", "High", "Biz", "", "check w/Pan on impact"),
    ("Feb-24", "SONiC presentation for Arista tiger team", "High", "span, lead", "", "building sonic knowledge across cisco's SE org"),
    ("Feb-24", "CLEU LTRSPG-2212 - year 2, FOSPN panel", "High", "industry, lead", "", ""),
    ("Feb-24", "Led MSFT multi-plane WAN rearchitecture discussions - SR, SRv6, multiple ISIS planes", "High", "biz", "", "multiple training & whiteboarding/workshop sessions"),
    ("Feb-24", '"Open Source Labbing" collaboration with Russ White of Akamai (and industry famous) - early containerlab adoptors, FR/SRv6', "", "", "", ""),
    ("Feb-24", "CIPOL: C/P/1035600/US/ORG/1: TITLE: CORE NETWORK SUPPORT FOR APPLICATION REQUESTED NETWORK SERVICE LEVEL OBJECTIVES - collab with SDWAN engineering", "High", "Innov, Span", "", "patent with SDWAN engineering team"),
    ("Feb-24", "Akamai SRv6 use cases w/Leddy, Russ", "", "", "", ""),
    ("Feb-24", "PA candidatacy consulting Masi, Allessandro", "High", "Lead", "", "Reviewed documents and advised both candidates on strengths and constructive ways to improve. Both were successful in attaining promotion to PSE"),
    ("Mar-24", "SL On Demand presentation to CX execs", "High", "Span, Innov, global", "", "Check with Subha D on impact"),
    ("Mar-24", "Continued engagement with google team of GDCE, PF, etc.", "Medium", "biz", "Mohit", "Check with Kartik S on impact"),
    ("Mar-24", "NaaS has become a common term and goal for SPs - Bell, Project Yukon (ATT, VZ), NetCo/ServCo", "High", "span, industry", "", 'A concept I first blogged about in future of SP networking, "cloud-like consumption of network services" became known in the industry as NaaS'),
    ("Mar-24", "PSE Subcommittee for Aavrinder Singh, Mike McPhee", "High", "lead", "", "PSE review subcommittee for both candidates. Mike McPhee was promoted"),
    ("Mar-24", "Geico sonic on 8000 - Dallas Hite, Eric Feschi", "High", "Span, Global, Biz", "", "Led sonic data center architectural engagement. Convinced BU to support a pricing model more akin to cloud/hyperscale as Geico infrastructure team was preparing to become a shared resource for all Berkshire Hathaway companies"),
    ("Mar-24", "Editor/Advisor to VZ SRv6 presentation at MPLS-WC", "High", "industry", "", "Having a Tier-1 operator like Verizon give essentially My presentation is much more impactful at a venue like MPLS World Congress"),
    ("Apr-24", "Cilium preso for ASP/Web w/Nico (april 26)", "High", "lead, span", "", "collaboration with mentee Nicolas Michel on a presentation for entire ASP/Web org. Great exposure for Nicolas"),
    ("Apr-24", "Began Adobe/Cilium engagement", "High", "global, span", "", "Dan Stacks, SE on Adobe, knew me from my STLDP leadership. His Cilium engagement was in trouble and he asked my help. I jumped in, built a model of Adobe's setup in my lab and was able to resolve all config/deployment issues and get the engagement back on track. Note, i had never worked with Isovalent Egress Gateway or load balancer products prior to the engagement, i simply taught myself as I went"),
    ("Apr-24", "Honeywell SR consulting", "High", "global, span", "James Lopez", "revenue impact?"),
    ("Apr-24", "Meta EBB - check w/Rodney on impact", "High", "Biz", "", "beginning of two year sales cycle"),
    ("May-24", "GDCE onsite - SRv6 design", "Medium", "biz", "", "check with Kartik S"),
    ("May-24", "Pourman's networking guest with Nico", "", "", "", ""),
    ("May-24", "TX Instruments SR network design consulting in Dallas - they wanted to hire me :)", "High", "biz", "Rekha", "check on revenue impact"),
    ("May-24", "Viasat SRv6 SFC design consulting", "", "", "Don Ewald", ""),
    ("Jun-24", "Web AI Fabrics design calculator and rail architectures", "High", "biz", "", "used by Web SE's for two years as a fabric design/scoping tool"),
    ("Jun-24", "Static uSID for Akamai", "", "", "Kamran", ""),
    ("Jun-24", "AI Tier-2 Investments consulting - Vladimirs Sazonovs, Lauren Johnson, Ryan Houska", "High", "span", "", "technical consultant for discussion around how Cisco should prioritize equity investment in Neoclouds"),
    ("Jun-24", "CIPOL: C/P/1035601/US/ORG/1: TITLE: UNDERLAY NETWORK TRAFFIC STEERING - w/SDWAN team", "High", "innov", "", ""),
    ("Jun-24", "Hoffman Singleton lab and design doc w/Chris Martin at Oracle", "", "", "", ""),
    ("Jul-24", "IETF Vancouver - Bernier (you guys are my 2030 guys), Luay @VZ", "", "", "", ""),
    ("Jul-24", "NYU HSRN sonic consulting", "Medium", "global", "", "check on revenue impact"),
    ("Jul-24", "Viasat Slicing/Service Chain SRv6 demo w/Chris Olson - was this also Qwilt?", "", "", "", ""),
    ("Aug-24", "Arkadius Cilium projects, MPLS-WC 2025, features developed, etc. (direct result from DC Champions preso in spring)", "High", "Biz, Span, Global, lead", "", ""),
    ("Aug-24", "OCI fast connect, MPLSoUDP", "", "", "", ""),
    ("Aug-24", "pitched Cilium for SRv6 Svc Chain control plane - CF, Thomas Graf, etc.", "High", "Innov, Span, Global", "", "Architectural agreement but no near term revenue pipeline so project was deferred"),
    ("Aug-24", "SRv6 for SSE - Rupak Chandra, archictural agreement, CIPOL", "High", "Innov, Span, Global", "", "early meetings which led to eventual addition of SRv6 support in Cisco's SASE/SSE product"),
    ("Aug-24", "Founding member SOSIE Project - a collaboration of DSEs and PSEs from GES, Public Sector, and ASP", "High", "Span, Global, Innov, Lead", "", ""),
    ("Sep-24", "Bell NaaS", "", "", "", ""),
    ("Sep-24", "SP DC Tiger Team - advisor", "", "", "", ""),
    ("Sep-24", "SR expansion into the Cloud - consulted with APJ / Rakuten (and other?) effort (Brendon Mifsud, Cris He)", "High", "Global, Innov", "", "check on impact"),
    ("Oct-24", "Evroc, Applied Digital, Lambda Labs - check w/accounts on impact", "Medium", "", "Johan, Josh Dahl, Bob G", "check on impact"),
    ("Oct-24", "The Trade Desk sonic consulting", "Medium", "", "Jorge Calixto", "check on impact"),
    ("Oct-24", "Ongoing collab with Joel Roberts - what was the impact", "Medium", "Global", "", "get LOR; check on impact"),
    ("Oct-24", "Viasat EBC - open source controller project", "Medium", "biz, innov", "", "check on impact"),
    ("Oct-24", "OCP conference - Oracle, MSFT, Voltage Park, Bell, Cloudflare - SRv6 for AI backend kickoff in earnest", "High", "Global, Industry, Span, Biz, Innov, Lead", "", "first public discussion with customers around SRv6 for AI backend"),
    ("Oct-24", "Jalapeno collab with Splunk James Schneider - did anything come of it?", "", "", "", ""),
    ("Oct-24", "Guest speaker presenting Isovalent to AI Compute SWAT team", "High", "span", "", "generate Isovalent internal knowledge and mindshare amongst a group of global thought leaders within cisco SE org"),
    ("Oct-24", "Adobe EGW POC rescue", "High", "global, span", "", ""),
    ("Nov-24", "Single OS findings/presentation document co-author", "", "", "", ""),
    ("Nov-24", "Web Stay ready Friday - Rob and I presented LTRSPG-2212 and led the Web Ses thru the lab", "High", "lead", "", ""),
    ("Nov-24", "TMo Overlay RFP", "medium", "biz", "", "check on impact"),
    ("Nov-24", "MSFT SRv6 for AI onsite workshop", "high", "biz, innov, industry", "", ""),
    ("Nov-24", "OCI SRv6 for AI - began engagement", "high", "biz, innov, industry", "", ""),
    ("Nov-24", "Eng hackathon with Zafar", "medium", "innov, span", "", "invited by Zafar Ali to partner on an AI themed hackathon. Produced an early version of the Jalapeno RPO SDN app"),
    ("Nov-24", "IMI VT speaker/lab: Cilium and SRv6: a Pathway to Cloud Native SP Network Services", "", "Global, Lead", "", "Check with Alex Lanin"),
    ("Nov-24", "Built first SRv6 for AI elephant flows demo - Brook, Josh, HQ team", "High", "innov", "", "2nd version of RPO app, which would later be used in VZ, AT&T and DLR engagements"),
    ("Nov-24", "Close coordination with SRv6 Eng team on sonic feature development - uSID forwarding, static uSIDs, BGP GRT, sonic-vpp, sonic-vs for testing, etc. This was a battle with MIG Eng from the start as they didn't believe the customer use case for several weeks if not months. I was instrumental in helping convince the BU that the use case was real, that openai was driving MSFT and OCI to invest in it, and that we needed to act now or fall further behind.", "High", "Innov, Span, Biz, Industry", "", ""),
    ("Dec-24", "Led OCI SRv6 workshop", "High", "biz", "", "OCI was running SRv6 in limited production by end of 2025"),
    ("Dec-24", "Carnegie Mellon/PSC sonic HSRN consulting", "High", "global", "Sarah Unruh", "check on impact"),
    ("Dec-24", "NYU sonic", "High", "global", "Saul Adler", "check on impact"),
    ("Dec-24", "Open source labbing part 2 with Russ White", "High", "Industry", "", "2nd live delivery of the pearson training with Russ"),
    ("Dec-24", "Began Christopher Luciano PSE mentoring", "High", "Lead", "", "Isovalent/Security SE"),
    ("Dec-24", "Cross Architecture friends - partnership, collaboration with Brian, John Cuneo, etc. Presented Cilium/Isovalent, solidified relationships and collab for years to come", "High", "Global, Span, Lead", "", "check on impact - Cigna AI factories in 2026?"),
    ("Jan-25", "Polarfly project with Chris Martin of OCI", "", "", "", ""),
    ("Jan-25", "CIPOL: C/P/1039921/US/ORG/1 TITLE: SYNTHETIC PATH TRACING OF SEGMENT ROUTED NETWORKS - collab with 1000Eyes Hans Ashlock", "High", "innov", "Hans Ashlock", "collaboration with ThousandEyes Hans Ashlock"),
    ("Jan-25", "Presented SONiC to VZ fellows Luay Jalil and Nick Morris", "Medium", "Biz, Span, industry", "Brad Ankenman", ""),
    ("Jan-25", "Presented on the Cisco CIPOL process to all of ASP - did anyone file a patent b/c of it?", "", "Lead, Span", "", "check on impact"),
    ("Jan-25", "consulted with Steve Wood (and Errol Roberts back in Nov/Dec) on Cilium and K8s - cloud-native SME that BU technical leaders reach out to when they want to get smarter on k8s, cilium, ebpf, etc.", "High", "Span", "", ""),
    ("Jan-25", "Began discussions ArangoDB Jalapeno network graph Josh", "High", "Innov", "", ""),
    ("Jan-25", "BYO lab - containerlab, vxr, etc. SEVT presentation/panel with Marty and Brent - sponsor Emerson, highest rated sessions of the entire SEVT", "High", "Lead, Span", "Emerson, Alex Lanin", ""),
    ("Jan-25", "SRv6 AI backend demo for OCI - uA on XRd", "High", "biz", "Jag Brar", "see OCI SRv6"),
    ("Jan-25", "SRv6 SDWAN sync amongst america's DSEs/PSEs", "", "", "Buresh", ""),
    ("Feb-25", "SGT end-to-end with steven moore", "", "Innov, Span", "", ""),
    ("Feb-25", "CLEU LTRSPG-2212 year 3", "", "industry, lead", "", ""),
    ("Feb-25", "DRIL - cilium/srv6 consulting with the team, assisted Pradeek Malik on cilium lab install", "High", "Innov, Span, Biz", "", ""),
    ("Mar-25", "Ebay EBC, sonic engagement", "High", "biz", "Ken Truong", "check on impact"),
    ("Mar-25", "PSE subcommittee member: Fausto V, Patrick LeMaistre,", "", "", "", ""),
    ("Mar-25", "Collab with Alberto Donzelli and Roque Gagliano on SRv6 Business Case for Jason Teller", "High", "Span, global", "", "check on impact"),
    ("Mar-25", "Akamai static uSID POC", "Medium", "Innov", "Leddy", "check on impact"),
    ("Mar-25", "Assisted/consulted Marina w/her Cilium/k8s/containerlab auto-bgp lab for CLUS", "High", "Span, global", "", "check on impact"),
    ("Mar-25", "MSFT SRv6 for frontend DC engagement begins - Mohan, Rockwell", "High", "Biz, Innov", "", "Multiple labs, multiple use cases, I used AI tools to rapidly generate lab scenarios with configs, topologies, docs, etc."),
    ("Mar-25", "SRv6 cilium for pub sector - Sam Rehling", "", "global", "", "check on impact"),
    ("Mar-25", "MPLS-WC and public presentation of SRv6 for AI backend - Rita Hui, also Kali's demo, Srv6 consulting with KPN, etc.", "High", "Global, Industry, Lead, Innov", "", ""),
    ("Apr-25", "Hosted and led SRv6 for DC internal cisco workshop April 8 - sales and BU leaders, guest speakers (MSFT, Alibaba), speaker lineup, presented cilium srv6, also post-workshop meetings onsite at MSFT, develop relationships with key engineers under rita like Abhishek Dosi", "High", "Global, Span, Industry, Lead, Innov", "", ""),
    ("Apr-25", "SRv6 lunch n learn with MSFT WAN team", "", "Biz", "", "check on impact"),
    ("Apr-25", "Josh and I presented SRv6 + SGT + ISE/SSE/SDWAN to Gillies - what was the impact?", "", "span, innov", "", "check on impact"),
    ("Apr-25", "Marina SEVT CAI containerlab/cilium session", "", "lead", "", "check on impact"),
    ("Apr-25", "Oracle EBC consulting sonic/solar-os team", "", "", "", ""),
    ("Apr-25", "Briefed Praveen B on srv6 for G200", "", "Innov, Span, Biz", "", ""),
    ("May-25", "Technical interview for open SE position on GCE - Furong Gisiger got it. I very often am called upon to perform or participate as an interviewer for open Web SE positions", "High", "Lead", "", ""),
    ("May-25", "MSFT SRv6 WAN lunch n learn part 2", "", "biz", "", "check on impact"),
    ("May-25", "CAI VT presenter: Move Faster Than Your Competition: Validate Customer Scenarios in Minutes and NOT Weeks", "", "Lead", "", "containerlab, byo-lab, AI tools, etc."),
    ("May-25", "Co-lead panel interview for Patrick L PSE", "High", "lead", "", "Patrick successfully achieved PSE promotion"),
    ("May-25", "MSFT SRv6 dc frontend workshop - lead 1/2 workshop on tech, use cases, etc.", "High", "biz", "", ""),
    ("Jun-25", "CLUS LTRMSI-3000, FSPN panel, NTT meetings, Isovalent party and Boost connections - gave Boost access to CL SRv6 lab after the fact where they POC'd SRv6 and determined it was to be there solution of the future. Coded a demo SRv6 pytorch plugin", "High", "industry, global, biz", "", ""),
    ("Jun-25", "Akamai PLX over ADC lab/demo/POC", "Medium", "innov", "", ""),
    ("Jun-25", "Digital Realty onsite workshop, presented Jalapeno", "High", "innov, biz", "", "DLR said a couple years ago they would've paid millions for something like Jalapeno"),
    ("Jun-25", "Adobe onsite Cilium workshop - proved out EGW and LB functionality and performance requirements", "High", "Biz, Span, Lead", "Dan Stacks", "check on revnue impact"),
    ("Jun-25", "Assisted Asoka with SONiC 8122 lab configurations for Oracle", "High", "biz", "", "ongoing project, 2026-2028 revenue projection?"),
    ("Jul-25", "Lambda Labs Isovalent Egress Transit GW concept and opportunity", "", "", "", ""),
    ("Jul-25", "consulted with account team for Lummi Nation possible FTTH ISP", "", "", "Ryan Hand", ""),
    ("Jul-25", "SRF LTRMSI part 1", "", "Lead", "", ""),
    ("Jul-25", "BE Interlock - responsible for IMI Web top asks, TAM, etc.", "", "Lead, Span", "", ""),
    ("Aug-25", "OCI 1000 GPU POC project kicks off - I consult some on sonic and later take ownership of SRv6 engagement", "High", "biz", "", ""),
    ("Aug-25", "SRv6 dc frontend POC development - 4PE, DCIX, mix of xr and sonic, demonstrated feasibilty for both prefix hiding/scale and SRv6-TE for inter-dc traffic", "High", "biz", "", "more msft frontend DC SRv6 work"),
    ("Aug-25", "Co-hosted 2nd annual US/China Web/Hyperscalers lunch at GSX", "High", "Global, Lead, Span", "", "relationship building with our Hyperscale peers in China"),
    ("Sep-25", "AT&T RPO POC planning, VZ A3PO and RPO POC planning", "", "Innov", "", ""),
    ("Sep-25", "Hawkv6 collab with Andreas, Bart V, and Severin", "Medium", "Innov, industry", "", "collaboration between EU SE's and OST university professor Severin Dellsberger on SRv6 innovation projects for critical infrastructure"),
    ("Sep-25", "Boost Isovalent SRv6 continued engagement", "", "", "", ""),
    ("Sep-25", "CIPOL: C/P/1038927/US/ORG/1: TITLE: SCHEDULED FIB TO ACCOUNT FOR INTERMITTENT CONNECTIVITY DUE TO ORBITAL DYNAMICS", "Medium", "Innov", "", "longer term applicability"),
    ("Sep-25", "Combatting Disagg with Network service innovation (SRv6) - set of presentations with BU for ASP audience", "High", "Biz, Span, Lead", "", "presentation to the full ASP team"),
    ("Sep-25", "Collab with EU DSE Virginia Teixeria: DCN+transport integration scenarios driven by AI; SRv6 from inside the DC; Cilium readiness, controller scale, DCN BU pushback on SRv6 inside DC", "High", "Global, Biz, Lead", "", "check on impact"),
    ("Sep-25", "Groq SRTE POC - flex-algo, data sovereignty", "Medium", "biz", "", "successful POC, but Groq got acquired by NVDA"),
    ("Sep-25", "Consult w/Disney architects on SR/SRTE design", "", "biz, global", "Marcin, Previn Wong", "check on impact"),
    ("Oct-25", "Collab with enterprise DSE Brian Shlisky on innovation projects - digital twin, graphs, etc.", "", "innov, span", "", "ongoing collaboration, including Live Protect on SONiC"),
    ("Oct-25", "As SRv6 gained momentum throughout 2025 I brokered many introductions between field SE's and Clarence Filsfils and the SR Eng team - Bob G, Marcin, Chris Olson, Mohit Vashisht, Nick Sischo, Joe Rockwell, Lokesh Khanna, etc.", "High", "Lead", "", "connector of SE's to distinguished and fellows"),
    ("Oct-25", "L4S/SRv6 collab with Humberto LaRoche and NYU", "", "Innov, Industry, Span", "", "check on impact"),
    ("Oct-25", "SONiC at VZ", "", "biz", "", "check with Jas"),
    ("Oct-25", "OCP - Web Ses dinner, meetings with MSFT SONiC/SRv6 team", "", "lead", "", ""),
    ("Oct-25", "Consulted with Visa on SR//SRv6 possibilities - RPO demo", "", "global, span, innov", "", "check with Dan Stacks"),
    ("Oct-25", "VZ SRv6 to the Host", "", "", "", ""),
    ("Oct-25", "TMC Innovation hour - SRv6 network service innovation - followup session", "High", "biz, lead", "", "followup, full ASP presentation"),
    ("Nov-25", "IETF - SRv6 host w/Nick Morris of Verizon", "", "", "", "mindshare building"),
    ("Nov-25", "BGP NFT/Ethereum CPOL filing", "medium", "innov", "", "collaboration with CAI SE John Cuneo, Ent DSE Brian Shlisky. CIPOL/Patent was denied."),
    ("Nov-25", "SRF LTRMSI 3000 part 2 - Bob loved the pytorch plugin", "High", "lead, biz", "", "delivered Cisco live lab training to Web SE team - continued development of SRv6, cloud native, sonic, and AI knowledge within the SE community"),
    ("Nov-25", "Isovalent and Telcos - Cilium SP business case/opportunity tracker", "High", "biz, span, global", "", "Cilium-SP use cases and opportunity/TAM tracker capturing opportunities from around the globe"),
    ("Dec-25", "ISE fully on board with SRv6 SGT and Secure Network Policy Framework", "High", "Innov, Span, Global, Biz", "", ""),
    ("Dec-25", "Pinnacle Award!", "High", "Innov, Span, Global, Biz", "", ""),
    ("Dec-25", "SRv6 DC workshop - hosted and organized workshop for bay area SEs and BU - followup from April with latest updates (80 attendees)", "High", "Span, Biz", "", ""),
    ("Dec-25", "STDLP - Satoshi Yamashita - my capstone project introduction", "High", "Lead", "", "mentor Satoshi through STLDP program"),
    ("Dec-25", "DC/Campus end-to-end EVPN tiger team", "", "", "", ""),
    ("Dec-25", "SONIC Cisco Secure Workload POC - developed/collab with Jason Maynard, Chris Crider, etc., Proved out CSW as a viable product to secure sonic infrastrcuture", "High", "Innov, Span, Global, Biz", "", "successful POC and collaboration with security SE specialist team of CSW as a form of Live Protect for SONiC"),
    ("Dec-25", "IMI VT building your own lab part 2 w/Marty", "High", "Lead, Span", "", "Marty and I were asked back to the VT for another 'build your own lab' session; check with Alex on score"),
    ("Jan-26", "Boost SRv6/Cloud Native workshop - led solution discussion", "High", "biz", "", "onsite 2 day workshop"),
    ("Jan-26", "Began mentoring Hiroyuki Sugano", "High", "Lead, Global", "", "IM&I SE specialist based in Japan"),
    ("Jan-26", "Practical SONiC nuggets with Santosh and John McCleod", "High", "Lead, Span, Biz", "", "Santosh's idea, I helped him develop it and recruit co-presenters, very successful series of short sonic training videos"),
    ("Jan-26", "Nutty Idea - Wanna share and get your thoughts - Don Ewald", "medium", "innov", "", "SDN/SmartSwitch brainstorm with Don E, SE on microsoft team"),
    ("Jan-26", "CHCN - with Riccardo", "medium", "innov", "", "SDN/full-NG architecture proposal - at this point I'm so well known for innovation across the company I get solicited by folks with new ideas, or folks with new ideas are referred to me for further brainstorming and development of their ideas. Riccardo's CHCN is very ambitious, i advised to scale back, use SRv6 uSID. he is currently developing a rich demo"),
    ("Jan-26", "SRv6 Roadshow planning team", "", "", "", ""),
    ("Jan-26", "MSFT dRH engagement", "High", "biz", "", "disaggregation of chassis-based T2 nodes into upper and lower pizzabox clos. All part of MSFT frontend DC re-architecture with SRv6"),
    ("Feb-26", "Nacho PSE submission - two major rewrites, sought reviews from outside experts - Vaughn, Marina, McPhee", "High", "lead", "", "I used my relationships across the company to get outside reviewers to review and provide comment/feedback"),
    ("Feb-26", "Dave Clough of WWT ongoing collab - what has been the impact and can I get a LOR", "", "Global, Span, Biz", "", ""),
    ("Feb-26", "Lightning talks episode 23 - perhaps the best one yet - what has been the impact", "", "lead", "", ""),
    ("Feb-26", "CLEU w/Nico - really high scores, Nico got Distinguished, MTE with New Brunswick, convinced them to accelerate transition to SRv6, introduced to Ianik and other resources", "High", "industry, lead", "", "cisco live EU, Nico got distinguished speaker!"),
    ("Feb-26", "Fiserv DC overlay and SRv6 presentation, consulting - Mahendra Singh", "", "Global, Biz", "", "check on impact"),
    ("Feb-26", "SRv6 for Videotron - consulting with AT, lab for Phillippe", "", "biz, lead", "", "new SE Philippe Vaillancourt - gave him access to my CL SRv6 lab so he could train himself and drive the videotron workshop"),
    ("Feb-26", "SRv6 end-to-end DC/NXOS tiger team w/Buresh, Marina, Varun, etc.", "medium", "Span, Innov", "", "collaboration with enterprise DSEs on scoping SRv6 customer user cases and TAM for Nexus platforms"),
    ("Feb-26", "Portfolio Innovation Areas SP/MIG - Craig Connors, Mike Lake, Errol, Vaugh, Marty", "", "Span, Innov", "", "Security BU leaders asked Vaughn, Marty, and myself to consult and brainstorm on possible innovation projects that would fit ASP/Web market"),
    ("Feb-26", "Coreweave EBC - VXR/Containerlab/SONiC lead", "", "", "", ""),
    ("Feb-26", "Nsight Isovalent presentation", "medium", "biz", "", "mindshare building"),
    ("Feb-26", "Comcast LB $5M consultation", "", "biz", "Jenelle", "check on impact"),
    ("Mar-26", "Cloudflare BMP - enhancements made it into 26.4.x?", "", "", "", ""),
    ("Mar-26", "SRv6 at OCI (and MSFT) - use cases, capabilities briefing for Anand Sridharan (ansi); Jason Bos (jbos); Sajay Vijayadharan (svijayad)", "high", "span", "", "briefing for MIG and silicon-1 engineering leadership on SRv6 use cases at MSFT and Oracle"),
    ("Mar-26", "Tech Elevate - SRv6 and cloud native - presented at both NA/EMEA and APJC timeslots", "high", "span, global", "", "delivered Cisco live SRv6 lab for SE's in EMEA and APJC across two sessions (get attendee counts)"),
    ("Mar-26", "SONiC field training workshop kickoff", "", "", "", ""),
    ("Mar-26", "SRv6 for Google AI Backend - intros, kickoff (Nick, Pablo, CF)", "medium", "biz, lead", "", "brokered introductions, however, Nick changed accounts. Followup with Kartik on next steps. MEMS?"),
    ("Mar-26", "dRH SRv6 vs. VXLAN and sonic GRT image/lab setup/POC for both Abhishek and Mohan", "high", "biz", "", "collaborated with Eng teams on presentation delivered to MSFT engineers on architectural options (SRv6 vs. VXLAN) for dRH architecture"),
    ("Mar-26", "Meta BBF lab - needed a VXR 8223 - not available yet, leveraged relationships with VXR team to get patch and install for Meta team", "high", "biz", "Asoka, Leif", "key enabler to help the SE team close the major deal"),
    ("Mar-26", "Developed containerlab and VXR lab setups and docs for Coreweave NetDev Eng - opportunity grew to 10k-12k switches", "medium", "biz", "", "check on impact"),
    ("Mar-26", "Cilium SP CRD document with progressive use cases from L3VPN to EGW to TGW", "high", "span, innov", "", "authored CRD document capturing use cases from across geos and lines of business"),
    ("Mar-26", "CLUS host networking collab with Chris Lapp", "high", "industry, lead", "", "co-developed a new cisco live breakout session on host-networking with fellow enthusiast Chris Lapp, a promising SE who is on PSE track - I'm not his official mentor, but I'm on his development team"),
    ("Mar-26", "Oracle SRv6 tutorial session part 1", "high", "biz", "", "SRv6 training for Oracle engineering teams"),
    ("Apr-26", "Oracle SRv6 tutorial session part 2", "high", "biz", "", "SRv6 training for Oracle engineering teams"),
    ("Apr-26", "Sonic nuggets go live", "", "lead, biz", "", ""),
    ("Apr-26", "Dan Stacks AI tool presented to HQ Arch staff meeting", "", "", "", "I often look for exposure opportunities for SE's who are doing great work. Their ideas roll up to the ASP/Web DSE/PSE group who are great at connecting them with other people, force multiplier"),
    ("Apr-26", "Kubecon CFP with Jesus Guzman Farjado", "high", "industry, lead", "", "awaiting word on whether our session proposal was selected"),
    ("May-26", "SRv6 multi-tenant design completed and reviewed with MSFT and Oracle", "high", "innov, biz, industry", "", "Lokesh Khanna, John McLeod, Joe Rockwell"),
    ("May-26", "Mock interviewer for PSE candidates from Security Sales", "high", "lead", "", "partnered with Mike McPhee (security PSE) to help develop both of our PSE mentees toward successful promotion"),
    ("May-26", "SRv6 MRC announced. I developed a PPT and emulator project, shared with MSFT and Oracle", "high", "innov, biz, industry", "", ""),
    ("May-26", "Ignacio PSE panel interview", "high", "lead", "", "went very well. Notification day is June 11"),
    ("May-26", "GSX IMI design clinic planning", "high", "span, lead", "", "co-leading design clinic training for SE's at upcoming GSX conference"),
    ("Jun-26", "Transitioned to Matt Gillies' Global Solutions Engineering team", "high", "span, global, lead", "", "I am lead Cloud-SP architect on the global team"),
    ("Jun-26", "Cisco Live US - panel, lab, host-based networking breakout session", "high", "industry, lead", "", ""),
    ("Jun-26", "STLDP mentee Satoshi turned in his pitch video", "high", "lead, span", "", "reviewed and provided feedback on video"),
    ("Jun-26", "EVPN Least Complexity project - began in Jan or Feb, multi-disciplinary tiger team of DSEs and PSEs examine enterprise DC, campus, and security for how we might offer a complete end-to-end solution with the least complexity. Readout to execs, include Jeetu Patel CPO that its basically impossible - firewalls do not support VXLAN-EVPN", "high", "span, lead", "", "my role: participant and lab validator that siloed management platforms add too much complexity"),
]

def main():
    head = CSV_PATH.read_text(encoding="utf-8").splitlines()
    # Keep through Dec-23 Cursor row (line 191, index 190)
    keep = head[:191]
    out_lines = keep + [""]
    # Write via csv to string then append
    import io
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    for row in ROWS_2024_PLUS:
        w.writerow(row)
    tail = buf.getvalue().rstrip("\n").split("\n")
    CSV_PATH.write_text("\n".join(keep + tail) + "\n", encoding="utf-8")
    print(f"Wrote {len(keep)} header+pre-2024 rows + {len(ROWS_2024_PLUS)} 2024+ rows = {len(keep)+len(ROWS_2024_PLUS)} total")

if __name__ == "__main__":
    main()
